log_dir: "Checkpoint_LibriTTS"
save_freq: 10
device: "cuda"
epochs: 120
batch_size: 64
pretrained_model: ""
load_only_params: False
train_data: "Data/ASR_Train_data_test.txt"
val_data: "Data/ASR_Val_data.txt"
num_workers: 8
data_augmentation: True
  
optimizer_params:
  lr: 0.0003
  
loss_params:
  lambda_f0: 0.01
  
