log_dir: "Checkpoint_GameTTS"
save_freq: 2
device: "cuda"
epochs: 150
batch_size: 32
pretrained_model: ""
train_data: ["Data/ASR_Train_data_test_kaggle.txt",]
val_data: ["Data/ASR_Val_data_kaggle.txt",]

preprocess_parasm:
  sr: 22050
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 95
   token_embedding_dim: 512

optimizer_params:
  lr: 0.0005
