log_dir: "Checkpoint_GameTTS"
save_freq: 5
device: "cuda"
epochs: 150
batch_size: 64
pretrained_model: ""
train_data: [
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/borderlands2_en.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/borderlands2_de.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/emotional_train.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/fallout4_en.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/gametts_de.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/kcd_de.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/sqnarrator.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/warcraft_en.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/witcher3_pl.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/witcher3_ru.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/witcher3_skyrim_en.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/worldofwarcraft.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/skyrim_jp.csv",
            "/home/alexander/Projekte/TTS_Data/metadata/filelists/libritts_train.csv",
        ]
val_data: [
          "/home/alexander/Projekte/TTS_Data/metadata/filelists/libritts_test.csv",
          "/home/alexander/Projekte/TTS_Data/metadata/filelists/pitch_test.csv"
          ]

preprocess_parasm:
  sr: 22050
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 95
   token_embedding_dim: 512

optimizer_params:
  lr: 0.0005
